# Generated by Django 4.2.27 on 2026-02-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="is_superadmin",
            new_name="is_superuser",
        ),
    ]
