# Generated by Django 4.2.27 on 2025-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
