import requests
import json
from django.conf import settings
# from django.contrib.auth.decorators import login_required
# example payload 
    # {
    #     "email": "student@example.com",
    #     "amount": 250000,  # in kobo (₦2500)
    #     "currency": "NGN",
    #     "channels": ["card", "bank_transfer", "bank", "ussd", "qr", "mobile_money"],
    #     "reference": "purchase_001_XYZ", # generated by developer
    #     "callback_url": "https://yourdomain.com/verify-paystack-payment/",
    #     "metadata": {
    #         "product_id": 42,
    #         "user_id": 7
    #     },
    #     "label": "Checkout For Product 1"
    # }


def check_out(payload):
    headers = {
                "Authorization": f"Bearer {settings.PAYSTACK_SECRET_KEY}",
                "Content-Type": "application/json"
    }

    response = requests.post(
        'https://api.paystack.co/transaction/initialize',
        headers=headers, 
        data=json.dumps(payload)
    )

    response_data = response.json()

    #sample response below
    # {
    #     "status": true,
    #     "message": "Authorization URL created",
    #     "data": {
    #         "authorization_url": "https://checkout.paystack.com/nkdks46nymizns7",
    #         "access_code": "nkdks46nymizns7",
    #         "reference": "nms6uvr1pl"
    #     }
    # }

    if response_data.get('status') == True:
        return True, response_data['data']['authorization_url']
    else: 
        return False, "Failed to initiate payment. Please try again later."
    

