# Generated by Django 4.2.27 on 2025-12-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="default.jpg", upload_to="uploads/category_picture"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("promo", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("promo_price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "image",
                    models.ImageField(
                        default="default.jpg", upload_to="uploads/product_picture"
                    ),
                ),
            ],
        ),
    ]
