# Generated by Django 4.2.27 on 2026-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("marketing", "Marketing"),
                            ("founder", "Founder"),
                        ],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/about_person")),
            ],
        ),
        migrations.CreateModel(
            name="AboutSiteHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/about_header")),
            ],
        ),
        migrations.CreateModel(
            name="AboutTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=155)),
                ("image", models.ImageField(upload_to="uploads/about_person")),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.TextField()),
            ],
        ),
    ]
