# Generated by Django 4.2.27 on 2025-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_available_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_level",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
