# Generated by Django 4.2.27 on 2025-12-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_similarproduct"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="similarproduct",
            options={"verbose_name_plural": " Similar Product"},
        ),
    ]
