# Generated by Django 4.2.27 on 2025-12-10 16:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_variation"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="variation",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
