# Generated by Django 4.2.27 on 2025-12-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_variation_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="variation",
            managers=[],
        ),
    ]
