# Generated by Django 4.2.27 on 2026-02-24 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="purchase_id",
            field=models.CharField(
                blank=True,
                default=uuid.UUID("1c57b493-6003-4347-b40d-0075de582994"),
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
