# Generated by Django 4.2.27 on 2026-01-08 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_orderhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderhistory",
            options={"verbose_name_plural": "Order History"},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="Payment_method",
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="purchase_id",
            field=models.CharField(
                blank=True,
                default=uuid.UUID("d71dc6d8-fe2c-462d-a8b2-667aa0a0b799"),
                max_length=225,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
