# Generated by Django 4.2.27 on 2026-02-28 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_orderhistory_purchase_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="purchase_id",
            field=models.CharField(
                blank=True,
                default=uuid.UUID("013aa202-dc43-4bb6-adf7-d88a42050a2c"),
                max_length=225,
                null=True,
            ),
        ),
    ]
