# Generated by Django 4.2.27 on 2026-01-08 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_orderhistory_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="size",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="purchase_id",
            field=models.CharField(
                blank=True,
                default=uuid.UUID("5a7b2b88-943f-4e34-a498-938b977ac136"),
                max_length=225,
                null=True,
            ),
        ),
    ]
