# Generated by Django 4.2.27 on 2026-01-08 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_variation_managers"),
        ("payment", "0004_remove_orderitem_color_remove_orderitem_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="purchase_id",
            field=models.CharField(
                blank=True,
                default=uuid.UUID("d361aca6-7bc1-4b5b-918d-d8c7fea70f7c"),
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.variation",
            ),
        ),
    ]
