# Generated by Django 4.2.27 on 2026-01-08 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_variation_managers"),
        ("payment", "0005_alter_orderhistory_purchase_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="purchase_id",
            field=models.CharField(
                blank=True,
                default=uuid.UUID("324b5a1e-75ab-45b4-9e5b-907003c1a299"),
                max_length=225,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="product.variation"),
        ),
    ]
