# Generated by Django 4.2.27 on 2026-01-15 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_alter_orderhistory_purchase_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="purchase_id",
            field=models.CharField(
                blank=True,
                default=uuid.UUID("8b73ede1-26d1-40d0-b7e1-e23f58beabd0"),
                max_length=225,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
